name: Feature Request
title: "[REQ] "
description: Suggest a feature that should be added
body:
  - type: markdown
    attributes:
      value: |
        ### **Preliminary instructions**
        - Please first check whether your idea has already been suggested in the [SleepStrap issues](https://github.com/SleepyDebug/SleepStrap/issues?q=is%3Aissue).
        - If your feature suggestion is to do with Roblox itself, please consider that what's possible is heavily constrained by what [FastFlags](https://github.com/pizzaboxer/bloxstrap/wiki/A-guide-to-FastFlags) are available.
  - type: textarea
    id: what-happened
    attributes:
      label: What idea do you have?
    validations:
      required: true
