name: CI (Debug)
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore -p:Platform=x64

    - name: Build
      run: dotnet build -p:Platform=x64 --no-restore

    - name: Publish
      run: dotnet publish -p:Platform=x64 -p:PublishSingleFile=true -p:CommitHash=${{ github.sha }} -p:CommitRef=${{ github.ref_type }}/${{ github.ref_name }} -r win-x64 -c Debug --self-contained false .\SleepStrap\SleepStrap.csproj

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: SleepStrap (Debug) (${{ github.sha }})
        path: .\SleepStrap\bin\x64\Debug\net6.0-windows10.0.19041.0\win-x64\publish\*
